<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="MAIN" Id="{267f4f9f-c3b1-4265-aa3a-a98afd343d60}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
    _fbCalculator : FbCalculator;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>